---
kind: pipeline
type: kubernetes
name: default

clone:
  depth: 1

steps:
# - name: build
#   image: rust:1.45.0-alpine3.11
#   volumes:
#   - name: cache
#     path: /cache
#   commands:
#   - apk add --no-cache musl-dev
#   - cargo build --verbose --target $RUST_TARGETS --release
#   environment:
#     RUST_TARGETS: x86_64-unknown-linux-musl
#     CARGO_TARGET_DIR: /cache

- name: release
  image: codingcoffee/aws
  volumes:
  - name: cache
    path: /cache
  commands:
  # - aws --endpoint-url https://minio.codingcoffee.me s3 cp /cache/x86_64-unknown-linux-musl/release/rusty s3://rusty/builds/
  - touch test.txt
  - echo $DRONE_SECRET_ENDPOINT
  - echo $AWS_ACCESS_KEY_ID
  - echo $AWS_SECRET_ACCESS_KEY
  - aws --endpoint-url https://minio.codingcoffee.me s3 cp test.txt s3://rusty/builds/
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  # depends_on:
  # - build

volumes:
- name: cache
  temp: {}

trigger:
  branch:
  - master

---

kind: secret
name: aws_access_key_id
get:
  path: drone-secrets
  name: AWS_ACCESS_KEY_ID

---

kind: secret
name: aws_secret_access_key
get:
  path: drone-secrets
  name: AWS_SECRET_ACCESS_KEY

...
