---
kind: pipeline
name: default

steps:
- name: test
  image: rust:1.45.0-alpine3.11
  commands:
  - apk add --no-cache musl-dev
  - cargo build --verbose --target $RUST_TARGETS --release
  - ls target/x86_64-unknown-linux-musl/release/rusty
  environment:
    RUST_TARGETS: x86_64-unknown-linux-musl
    PACKAGE_NAME: rusty

trigger:
  branch:
  - master
...
